/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
    Command: npx gltfjsx@6.5.0 react.glb -T
    Author: xenadus (https://sketchfab.com/xenadus)
    License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
    Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
*/

import { Float, useGLTF } from "@react-three/drei";
import { useFrame, type ThreeElements } from "@react-three/fiber";
import { useRef } from "react";
import * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["React-Logo_Material002_0"]: THREE.Mesh;
  };
  materials: {
    ["Material.002"]: THREE.MeshStandardMaterial;
  };
};

// Logo half-width (~0.9) plus breathing room from the viewport edge
const EDGE_PADDING = 4.5;
// Camera distance when the hero is at rest (see HeroCamera)
const REST_CAMERA_Z = 20;

interface ReactLogoProps extends Omit<ThreeElements["group"], "position"> {
  position: [number, number, number];
}

export const ReactLogo = ({ position, ...props }: ReactLogoProps) => {
  const { nodes, materials } = useGLTF(
    "/models/react.glb"
  ) as unknown as GLTFResult;

  const groupRef = useRef<THREE.Group>(null);

  // Keep the logo inside the visible area on narrow/tall viewports.
  // Measured from the resting camera so the scroll zoom doesn't drag it inward.
  useFrame((state) => {
    if (!groupRef.current) return;

    const { fov } = state.camera as THREE.PerspectiveCamera;
    const height =
      2 *
      Math.tan(THREE.MathUtils.degToRad(fov / 2)) *
      (REST_CAMERA_Z - position[2]);
    const width = height * (state.size.width / state.size.height);
    const maxX = Math.max(width / 2 - EDGE_PADDING, 0);
    groupRef.current.position.x = Math.min(Math.max(position[0], -maxX), maxX);
  });

  return (
    <Float floatIntensity={1}>
      <group
        ref={groupRef}
        position={position}
        scale={0.4}
        {...props}
        dispose={null}
      >
        <mesh
          geometry={nodes["React-Logo_Material002_0"].geometry}
          material={materials["Material.002"]}
          position={[0, 0.079, 0.181]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.392, 0.392, 0.527]}
        />
      </group>
    </Float>
  );
};

useGLTF.preload("/models/react.glb");
